name: Build Flutter Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi --release
      - uses: actions/upload-artifact@v3
        with:
          name: app-release-split
          path: build/app/outputs/flutter-apk/release

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v3
        with:
          name: windows-app
          path: build/windows/runner/Release

  create-release:
    needs: [build-apk, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-release-split
          path: release/apk
      - uses: actions/download-artifact@v3
        with:
          name: windows-app
          path: release/windows
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            release/apk/**
            release/windows/runner.exe
