name: Build Flutter Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4  # Cache Flutter SDK and dependencies
        with:
          path: |
            ~/.pub-cache/hosted/pub.dartlang.org
            /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi --release
      - uses: actions/upload-artifact@v4  # Upload specific APK (example: arm64-v8a)
        with:
          name: app-release-arm64-v8a
          path: build/app/outputs/flutter-apk/release/app-arm64-v8a-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4  # Cache Flutter SDK and dependencies
        with:
          path: |
            ~/.pub-cache/hosted/pub.dartlang.org
            /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
      - run: flutter pub get
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/x64/runner/Release

  create-release:
    waits-for: [build-apk, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-release-arm64-v8a
          path: release/apk
      - uses: actions/download-artifact@v4
        with:
          name: windows-app
          path: release/windows
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  
        with:
          files: |
            release/apk/**
            release/windows/runner.exe